name: Check

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML5Validator
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          # FIXME
          #blacklist: invalid
          blacklist: '*.html' # Skipping all HTML files for now until all issues are sorted out.
          css: true
